// Code generated by tygo. DO NOT EDIT.

//////////
// source: models.go

export interface Message {
  type: string;
  payload: { [key: string]: any};
  timestamp: number /* int64 */;
}
export interface Player {
  id: string;
  name: string;
  isReady: boolean;
  characters: Character[];
}
export interface Character {
  pos: Coordinate;
  rotation: number /* int64 */;
}
export interface Coordinate {
  x: number /* int16 */;
  y: number /* int16 */;
}
